export * from './user.entity';
export * from './role.entity';
export * from './menu.entity';
export * from './submenu.entity';
export * from './permission.entity';
export * from './parameter.entity';
export * from './parameter-types.entity';
export * from './patients.entity';
export * from './services.entity';
export * from './sale.entity';
export * from './sub-services.entity';
export * from './specialty.entity';
export * from './appointment.entity';
export * from './doctor-schedule.entity';
export * from './maestroproducto.entity'
export * from './schedule.entity';
