export enum ErrorCode {
	/**
	 * CUANDO YA SE ENCONTRO EL DNI EN PACIENTE
	 */
	PATIENT_DNI_ALREADY_EXISTS = 601,
	/**
	 * ERROR TOKEN RENIEC
	 */
	ERROR_TOKEN_RENIEC = 602,

	/**
	 * ERROR DE USUARIO DESACTIVADO
	 */
	ERROR_USER_INACTIVE = 603,

	ERROR_CREDENTIALS_INCORRECTS = 604,

	ERROR_USER_NOT_FOUND = 605,
}
